
permalink:           pretty
# Setup
title:               'Компьютерные технологии в механике'
homepage_title:      Home
url:                 https://iomguy.github.io/PythonIntroCourse2020/
baseurl:             '/PythonIntroCourse2020'

src:                 "."
default_theme:       "rust"

# For Maths
markdown:            kramdown
 
prologues:
  - path: 1_semester.md
  - path: about.md
  - path: tools.md
  - path: data_pages/7_git_branches_and_remote.pdf
  - path: data_pages/8_regex.pdf
  - path: data_pages/10_iterators_generators_list_comprehension.pdf
# chapters:
#  - path: week01/01.md
#    sections:
#      - path: tools.md
#      - path: week01/01-2.md